apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"devops-demo-service","namespace":"default"},"spec":{"ports":[{"nodePort":30007,"port":3000,"protocol":"TCP","targetPort":3000}],"selector":{"app":"devops-demo-app"},"type":"NodePort"}}
  creationTimestamp: "2026-05-15T08:49:07Z"
  name: devops-demo-service
  namespace: default
  resourceVersion: "1145"
  uid: c3b4397c-2dc5-4d63-a631-ee017314d30e
spec:
  clusterIP: 10.103.147.66
  clusterIPs:
  - 10.103.147.66
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30007
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: devops-demo-app
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}